### ISSUE TITLE
validator depends on ruby-dev

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/validator-short-read-assembler#34]
The validator debepends on ffi that depends on ruby-dev.
If ruby-dev is not installed the validator reports:

``` shell
+++ dirname ./validate-short-read-assembler/validate
++ cd ./validate-short-read-assembler
++ pwd
+ SELFDIR=/home/pbelmann/test/test_ruby/validate-short-read-assembler
+ '[' '!' -f /home/pbelmann/test/test_ruby/validate-short-read-assembler/Gemfile.lock ']'
+ cd /home/pbelmann/test/test_ruby/validate-short-read-assembler
+ bundle install
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from extconf.rb:4:in `<main>'


Gem files will remain installed in /tmp/bundler20150510-23115-942px0/ffi-1.9.8/gems/ffi-1.9.8 for inspection.
Results logged to /tmp/bundler20150510-23115-942px0/ffi-1.9.8/gems/ffi-1.9.8/ext/ffi_c/gem_make.out
An error occurred while installing ffi (1.9.8), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.8'` succeeds before bundling.
```

When I run the suggested command `gem install ffi -v '1.9.8` it reports:

``` shell
Building native extensions.  This could take a while...
ERROR:  Error installing ffi:
        ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from extconf.rb:4:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.8 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/ffi-1.9.8/ext/ffi_c/gem_make.out
```

This due to the missing ruby-dev package. But this is not clear from the message.

A patch for this issue might be a pre check in the shell script.

**Comment by pbelmann** [comment]
**Update:**

I cannot reproduce this report. It works even without ruby-dev. So I will close this issue until we face this issue again.

**Comment by michaelbarton** [comment]
If this happens again, or becomes a recurrent problem, we have a couple of options -
- Use travelling ruby - http://phusion.github.io/traveling-ruby/
- Rewrite the aruba command line testing in python and compile a binary similarly to the file validator.
